language: erlang
otp_release:
  - 25.0
  - 24.3.4.1
  - 23.3.4.14
  - 22.3.2
  - 21.3.8

install: wget https://github.com/erlang/rebar3/releases/download/3.13.1/rebar3 && chmod 755 rebar3

script: ./rebar3 update && ./rebar3 ct && ./rebar3 dialyzer && ./rebar3 coveralls send
